branch-defaults:
  default:
    environment: zazoSqsWorker-env
global:
  application_name: zazo_sqs_worker
  default_ec2_keyname: ec2
  default_platform: Ruby 2.0 (Passenger Standalone)
  default_region: us-west-1
  profile: eb-cli
