FORMAT: 1A

# Events [/api/v1/messages]

## Index [GET]

+ Parameters
    + sender_id: fxVPRkGICwnrAwym52gK (string, optional) - Filter messages by sender
    + receiver_id: 7qdanSEmctZ2jPnYA0a1 (string, optional) - Filter messages by receiver
    + reverse: (boolean, optional) - Order in reverse. Default is by `triggered_at ASC`.
        + Default: false
    + page: 1 (number, optional) - Set page for fetch (100 events per page).
        + Default: 1
    + per: 1 (number, optional) - Number of records per page
        + Default: 100


+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    + Body

        [
            {
                "id": "25bGO6mmNEmQmKbvrnj1-j8WAdT1Kxqb0WQGBp30v-815dabd1540103ce39fa8c182c9889e5",
                "sender_id": "25bGO6mmNEmQmKbvrnj1",
                "receiver_id": "j8WAdT1Kxqb0WQGBp30v",
                "uploaded_at": "2015-05-04T23:20:35.200Z",
                "file_name": "25bGO6mmNEmQmKbvrnj1-j8WAdT1Kxqb0WQGBp30v-815dabd1540103ce39fa8c182c9889e5",
                "file_size": 96604,
                "status": "uploaded",
                "delivered": false,
                "complete": false,
                "missing_events": [
                    [
                        "video",
                        "kvstore",
                        "received"
                    ],
                    [
                        "video",
                        "notification",
                        "received"
                    ],
                    [
                        "video",
                        "kvstore",
                        "downloaded"
                    ],
                    [
                        "video",
                        "notification",
                        "downloaded"
                    ],
                    [
                        "video",
                        "kvstore",
                        "viewed"
                    ],
                    [
                        "video",
                        "notification",
                        "viewed"
                    ]
                ]
            },
            {
                "id": "25bGO6mmNEmQmKbvrnj1-tceDMXCQDbBWaKhhAhc5-0390c02cfae30b2b54fe5e789ff8fb54",
                "sender_id": "25bGO6mmNEmQmKbvrnj1",
                "receiver_id": "tceDMXCQDbBWaKhhAhc5",
                "uploaded_at": "2015-05-04T23:20:52.867Z",
                "file_name": "25bGO6mmNEmQmKbvrnj1-tceDMXCQDbBWaKhhAhc5-0390c02cfae30b2b54fe5e789ff8fb54",
                "file_size": 190713,
                "status": "uploaded",
                "delivered": false,
                "complete": false,
                "missing_events": [
                    [
                        "video",
                        "kvstore",
                        "received"
                    ],
                    [
                        "video",
                        "notification",
                        "received"
                    ],
                    [
                        "video",
                        "kvstore",
                        "downloaded"
                    ],
                    [
                        "video",
                        "notification",
                        "downloaded"
                    ],
                    [
                        "video",
                        "kvstore",
                        "viewed"
                    ],
                    [
                        "video",
                        "notification",
                        "viewed"
                    ]
                ]
            },
            {
                "id": "25bGO6mmNEmQmKbvrnj1-VPO8LSmr8FD3vLhHFYQN-527233cc5fccf31805d2e65673f339b7",
                "sender_id": "25bGO6mmNEmQmKbvrnj1",
                "receiver_id": "VPO8LSmr8FD3vLhHFYQN",
                "uploaded_at": "2015-05-04T23:21:17.788Z",
                "file_name": "25bGO6mmNEmQmKbvrnj1-VPO8LSmr8FD3vLhHFYQN-527233cc5fccf31805d2e65673f339b7",
                "file_size": 106467,
                "status": "uploaded",
                "delivered": false,
                "complete": false,
                "missing_events": [
                    [
                        "video",
                        "kvstore",
                        "received"
                    ],
                    [
                        "video",
                        "notification",
                        "received"
                    ],
                    [
                        "video",
                        "kvstore",
                        "downloaded"
                    ],
                    [
                        "video",
                        "notification",
                        "downloaded"
                    ],
                    [
                        "video",
                        "kvstore",
                        "viewed"
                    ],
                    [
                        "video",
                        "notification",
                        "viewed"
                    ]
                ]
            }
        ]


# Show [GET /api/v1/messages/{id}]

+ Parameters

    + id: `fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960` (string) - ID of message

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
            "id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
            "sender_id": "fxVPRkGICwnrAwym52gK",
            "receiver_id": "7qdanSEmctZ2jPnYA0a1",
            "uploaded_at": "2015-05-06T15:27:59.291Z",
            "file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
            "file_size": 270864,
            "status": "viewed",
            "delivered": true,
            "complete": true,
            "missing_events": []
        }

# Events [GET /api/v1/messages/{id}/events]

+ Parameters

    + id: `fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960` (string) - ID of message

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

    + Body

        [
            {
                "id": 29736,
                "name": [
                    "video",
                    "s3",
                    "uploaded"
                ],
                "triggered_at": "2015-05-06T15:27:59.291Z",
                "triggered_by": "aws:s3",
                "initiator": "s3",
                "initiator_id": null,
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960"
                },
                "raw_params": {
                    "eventVersion": "2.0",
                    "eventSource": "aws:s3",
                    "awsRegion": "us-west-1",
                    "eventTime": "2015-05-06T15:27:59.291Z",
                    "eventName": "ObjectCreated:Put",
                    "userIdentity": {
                        "principalId": "AWS:AIDAIUFT72XFHDTJOMRJW"
                    },
                    "requestParameters": {
                        "sourceIPAddress": "213.169.66.130"
                    },
                    "responseElements": {
                        "x-amz-request-id": "8349EDA9DA7B0991",
                        "x-amz-id-2": "KNLtuYUT5\/BGmD4PjbL\/IfNROPdGw9Vc1N1fBdaChJTM+mLoyQzMr0zBiMUo\/U9yhdAsqx0OpSo="
                    },
                    "s3": {
                        "s3SchemaVersion": "1.0",
                        "configurationId": "zazo-videos-to-sqs",
                        "bucket": {
                            "name": "videos.zazo.com",
                            "ownerIdentity": {
                                "principalId": "A2MSYRMSE88G92"
                            },
                            "arn": "arn:aws:s3:::videos.zazo.com"
                        },
                        "object": {
                            "key": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                            "file_size": 270864,
                            "eTag": "703cdde8e407571420c7712e1491b08f"
                        }
                    }
                },
                "created_at": "2015-05-06T15:27:59.395Z",
                "updated_at": "2015-05-06T15:27:59.395Z",
                "message_id": "3d7b75f5-c2fe-4ab0-bf92-592b59d1ee1a"
            },
            {
                "id": 29738,
                "name": [
                    "video",
                    "notification",
                    "received"
                ],
                "triggered_at": "2015-05-06T15:27:59.754Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "from_mkey": "fxVPRkGICwnrAwym52gK",
                    "sender_name": "Alex",
                    "target_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "video_id": "1430926059657"
                },
                "created_at": "2015-05-06T15:27:59.831Z",
                "updated_at": "2015-05-06T15:27:59.831Z",
                "message_id": "21860ed7-c41b-4a3c-80aa-dadb303cbd4f"
            },
            {
                "id": 29737,
                "name": [
                    "video",
                    "kvstore",
                    "received"
                ],
                "triggered_at": "2015-05-06T15:27:59.758Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "key1": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-63edf4e66cc521c4ad19b5124f255388-VideoIdKVKey",
                    "key2": "1430926059657",
                    "value": "{\"videoId\":\"1430926059657\"}"
                },
                "created_at": "2015-05-06T15:27:59.830Z",
                "updated_at": "2015-05-06T15:27:59.830Z",
                "message_id": "90636ea1-fdca-4bd1-93f0-5352abd13ffd"
            },
            {
                "id": 29742,
                "name": [
                    "video",
                    "kvstore",
                    "downloaded"
                ],
                "triggered_at": "2015-05-06T15:28:05.765Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "key1": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-63edf4e66cc521c4ad19b5124f255388-VideoStatusKVKey",
                    "key2": null,
                    "value": "{\"videoId\":\"1430926059657\",\"status\":\"downloaded\"}"
                },
                "created_at": "2015-05-06T15:28:05.821Z",
                "updated_at": "2015-05-06T15:28:05.821Z",
                "message_id": "bfa9b6d9-3ca6-4073-ae46-41130a7ac2d5"
            },
            {
                "id": 29743,
                "name": [
                    "video",
                    "notification",
                    "downloaded"
                ],
                "triggered_at": "2015-05-06T15:28:05.848Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "target_mkey": "fxVPRkGICwnrAwym52gK",
                    "to_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "status": "downloaded",
                    "video_id": "1430926059657"
                },
                "created_at": "2015-05-06T15:28:05.896Z",
                "updated_at": "2015-05-06T15:28:05.896Z",
                "message_id": "9123fc3e-e7f5-4057-9f22-1ad7cab7ce16"
            },
            {
                "id": 29744,
                "name": [
                    "video",
                    "kvstore",
                    "viewed"
                ],
                "triggered_at": "2015-05-06T15:28:07.727Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "key1": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-63edf4e66cc521c4ad19b5124f255388-VideoStatusKVKey",
                    "key2": null,
                    "value": "{\"videoId\":\"1430926059657\",\"status\":\"viewed\"}"
                },
                "created_at": "2015-05-06T15:28:07.787Z",
                "updated_at": "2015-05-06T15:28:07.787Z",
                "message_id": "11cc23af-7997-479a-867e-2a014cc0b0b1"
            },
            {
                "id": 29745,
                "name": [
                    "video",
                    "notification",
                    "viewed"
                ],
                "triggered_at": "2015-05-06T15:28:07.853Z",
                "triggered_by": "zazo:api",
                "initiator": "user",
                "initiator_id": "fxVPRkGICwnrAwym52gK",
                "target": "video",
                "target_id": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                "data": {
                    "sender_id": "fxVPRkGICwnrAwym52gK",
                    "receiver_id": "7qdanSEmctZ2jPnYA0a1",
                    "video_file_name": "fxVPRkGICwnrAwym52gK-7qdanSEmctZ2jPnYA0a1-568a66958adfcd2d43a46fcdccf67960",
                    "video_id": "1430926059657"
                },
                "raw_params": {
                    "target_mkey": "fxVPRkGICwnrAwym52gK",
                    "to_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "status": "viewed",
                    "video_id": "1430926059657"
                },
                "created_at": "2015-05-06T15:28:07.895Z",
                "updated_at": "2015-05-06T15:28:07.895Z",
                "message_id": "5f456c93-1231-445c-a04c-970e31ae4021"
            }
        ]
