FORMAT: 1A

# Metrics [/api/v1/metrics]

## Index [GET /api/v1/metrics]

+ Response 200 (application/json; charset=utf-8)

    + Body

        [
          {
            "name": "active_users",
            "type": "aggregated_by_timeframe"
          },
          {
            "name": "aggregate_messaging_info",
            "type": "aggregated"
          },
          {
            "name": "messages_sent",
            "type": "aggregated_by_timeframe"
          },
          {
            "name": "usage_by_active_users",
            "type": "aggregated_by_timeframe"
          },
          {
            "name": "user_activity",
            "type": "aggregated"
          }
        ]

## Show metric [POST /api/v1/metrics/{id}]

+ Parameters

    + id: messages_sent (string) - ID of metric

### Messages Sent [POST /api/v1/metrics/messages_sent]

+ Parameters

    + group_by: (enum[string], optional) - Time frame for grouping
        + Default: day
        + Members:
            + day - group by day
            + week - group by week
            + month - group by month

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
          "2015-05-04 00:00:00 UTC": 42,
          "2015-05-05 00:00:00 UTC": 1094,
          "2015-05-06 00:00:00 UTC": 820,
          "2015-05-07 00:00:00 UTC": 845,
          "2015-05-08 00:00:00 UTC": 828,
          "2015-05-09 00:00:00 UTC": 924,
          "2015-05-10 00:00:00 UTC": 713,
          "2015-05-11 00:00:00 UTC": 317,
          "2015-05-12 00:00:00 UTC": 551,
          "2015-05-13 00:00:00 UTC": 574,
          "2015-05-14 00:00:00 UTC": 490,
          "2015-05-15 00:00:00 UTC": 705,
          "2015-05-16 00:00:00 UTC": 460,
          "2015-05-17 00:00:00 UTC": 208,
          "2015-05-18 00:00:00 UTC": 296,
          "2015-05-19 00:00:00 UTC": 376,
          "2015-05-20 00:00:00 UTC": 235,
          "2015-05-21 00:00:00 UTC": 591,
          "2015-05-22 00:00:00 UTC": 423,
          "2015-05-23 00:00:00 UTC": 445,
          "2015-05-24 00:00:00 UTC": 226,
          "2015-05-25 00:00:00 UTC": 243,
          "2015-05-26 00:00:00 UTC": 216,
          "2015-05-27 00:00:00 UTC": 344,
          "2015-05-28 00:00:00 UTC": 328
        }

## Active Users [POST /api/v1/metrics/active_users]

+ Parameters

    + group_by: (enum[string], optional) - Time frame for grouping
        + Default: day
        + Members:
            + day - group by day
            + week - group by week
            + month - group by month

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
          "2015-05-06 00:00:00 UTC": 122,
          "2015-05-25 00:00:00 UTC": 64,
          "2015-05-05 00:00:00 UTC": 152,
          "2015-05-07 00:00:00 UTC": 134,
          "2015-05-08 00:00:00 UTC": 152,
          "2015-05-09 00:00:00 UTC": 154,
          "2015-05-10 00:00:00 UTC": 126,
          "2015-05-11 00:00:00 UTC": 105,
          "2015-05-14 00:00:00 UTC": 102,
          "2015-05-15 00:00:00 UTC": 114,
          "2015-05-16 00:00:00 UTC": 90,
          "2015-05-20 00:00:00 UTC": 70,
          "2015-05-21 00:00:00 UTC": 93,
          "2015-05-22 00:00:00 UTC": 84,
          "2015-05-24 00:00:00 UTC": 57,
          "2015-05-27 00:00:00 UTC": 71,
          "2015-05-12 00:00:00 UTC": 120,
          "2015-05-13 00:00:00 UTC": 103,
          "2015-05-19 00:00:00 UTC": 60,
          "2015-05-26 00:00:00 UTC": 61,
          "2015-05-28 00:00:00 UTC": 66,
          "2015-05-17 00:00:00 UTC": 77,
          "2015-05-18 00:00:00 UTC": 72,
          "2015-05-23 00:00:00 UTC": 69,
          "2015-05-04 00:00:00 UTC": 14
        }

### Usage by Active Users [POST /api/v1/metrics/usage_by_active_users]

+ Parameters

    + group_by: (enum[string], optional) - Time frame for grouping
        + Default: day
        + Members:
            + day - group by day
            + week - group by week
            + month - group by month

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
          "2015-05-04 00:00:00 UTC": 3.0,
          "2015-05-05 00:00:00 UTC": 7.197368421052632,
          "2015-05-06 00:00:00 UTC": 7.0085470085470085,
          "2015-05-07 00:00:00 UTC": 7.222222222222222,
          "2015-05-08 00:00:00 UTC": 6.46875,
          "2015-05-09 00:00:00 UTC": 7.162790697674419,
          "2015-05-10 00:00:00 UTC": 7.505263157894737,
          "2015-05-11 00:00:00 UTC": 4.731343283582089,
          "2015-05-12 00:00:00 UTC": 6.191011235955056,
          "2015-05-13 00:00:00 UTC": 7.08641975308642,
          "2015-05-14 00:00:00 UTC": 6.447368421052632,
          "2015-05-15 00:00:00 UTC": 8.19767441860465,
          "2015-05-16 00:00:00 UTC": 6.216216216216216,
          "2015-05-17 00:00:00 UTC": 3.8518518518518516,
          "2015-05-18 00:00:00 UTC": 4.933333333333334,
          "2015-05-19 00:00:00 UTC": 8.173913043478262,
          "2015-05-20 00:00:00 UTC": 4.519230769230769,
          "2015-05-21 00:00:00 UTC": 8.32394366197183,
          "2015-05-22 00:00:00 UTC": 6.507692307692308,
          "2015-05-23 00:00:00 UTC": 8.557692307692308,
          "2015-05-24 00:00:00 UTC": 5.136363636363637,
          "2015-05-25 00:00:00 UTC": 5.170212765957447,
          "2015-05-26 00:00:00 UTC": 4.909090909090909,
          "2015-05-27 00:00:00 UTC": 5.830508474576271,
          "2015-05-28 00:00:00 UTC": 6.452830188679245
        }

### Aggregate Messaging Info [POST /api/v1/metrics/aggregate_messaging_info]

+ Parameters

    + user_id: fxVPRkGICwnrAwym52gK (string) - ID of user.
    + friend_id: 7qdanSEmctZ2jPnYA0a1 (string, optional) - ID of friend.
        If set, returns data for messages from user to friend (outgoing) and in reverse (incoming).

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
          "outgoing": {
            "total_sent": 41,
            "total_received": 40,
            "undelivered_percent": 2.4390243902439024
          },
          "incoming": {
            "total_sent": 70,
            "total_received": 48,
            "undelivered_percent": 31.428571428571427
          }
        }

### Sent Messages Count By Period [POST /api/v1/metrics/messages_count_by_period]

+ Parameters

    + users_ids: [fxVPRkGICwnrAwym52gK] (array of strings) - IDs of users.
    + group_by: (enum[string], optional) - Time frame for grouping
        + Default: day
        + Members:
            + day - group by day
            + week - group by week
            + month - group by month
    + since: 2015-05-25 00:00:00 (string, optional) - Start datetime

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
          "fxVPRkGICwnrAwym52gK": {
            "2015-05-21 00:00:00 UTC": 13,
            "2015-05-24 00:00:00 UTC": 2,
            "2015-05-26 00:00:00 UTC": 1,
            "2015-05-27 00:00:00 UTC": 2
          }
        }

### Video uploads duplications by sender_id [POST /api/v1/metrics/upload_duplications]

+ Response 200 (application/json; charset=utf-8)

    + Body

        [
            {
                "sender_id": "7qdanSEmctZ2jPnYA0a1",
                "count": 961
            },
            {
                "sender_id": "oRXc4Q9pIkTZXYDtQka6",
                "count": 254
            },
            {
                "sender_id": "0JviygYehuUCOwY8TsMm",
                "count": 132
            },
            {
                "sender_id": "aTgcP52EcZr2rylLaUQY",
                "count": 84
            },
            {
                "sender_id": "j8WAdT1Kxqb0WQGBp30v",
                "count": 80
            },
            {
                "sender_id": "czxnpPGc3NNM73JpwV5e",
                "count": 74
            },
            {
                "sender_id": "qIkFgWmzrf3PIXmbuei6",
                "count": 72
            },
            {
                "sender_id": "Zyn4wXTIsTpNW9UbprU6",
                "count": 68
            },
            {
                "sender_id": "FTDphoB71bl0mwTpL55z",
                "count": 63
            }
        ]

### Calculates count of incomplete and unviewed messages by direction [POST /api/v1/metrics/messages_statuses_between_users]

Returns data for messages from user to friend (`outgoing`) and in reverse (`incoming`).

+ Parameters

    + user_id: fxVPRkGICwnrAwym52gK (string) - ID of user.
    + friend_ids: [7qdanSEmctZ2jPnYA0a1, 0DAQEVtmNKQiW6aoQrvo] (enum[string]) - IDs of friends.

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
            "total": {
                "outgoing": {
                    "sent": 59,
                    "incomplete": 4,
                    "unviewed": 3
                },
                "incoming": {
                    "sent": 82,
                    "incomplete": 6,
                    "unviewed": 6
                }
            },
            "7qdanSEmctZ2jPnYA0a1": {
                "outgoing": {
                    "sent": 39,
                    "incomplete": 2,
                    "unviewed": 2
                },
                "incoming": {
                    "sent": 60,
                    "incomplete": 6,
                    "unviewed": 6
                }
            },
            "0DAQEVtmNKQiW6aoQrvo": {
                "outgoing": {
                    "sent": 20,
                    "incomplete": 2,
                    "unviewed": 1
                },
                "incoming": {
                    "sent": 22,
                    "incomplete": 0,
                    "unviewed": 0
                }
            }
        }

### Message failures analysis in time frame [POST /api/v1/metrics/messages_failures]

+ Parameters

    + start_date: 2015-06-25 (string, optional) - Start date
      Default: 12.days.ago

    + end_date: 2015-07-05 (string, optional) - End date
      Default: 2.days.ago

+ Response 200 (application/json; charset=utf-8)

    + Body

        {
            "uploaded": 2057,
            "delivered": 1907,
            "undelivered": 150,
            "incomplete": 25,
            "missing_kvstore_received": 149,
            "missing_notification_received": 196,
            "missing_kvstore_downloaded": 252,
            "missing_notification_downloaded": 254,
            "missing_kvstore_viewed": 242,
            "missing_notification_viewed": 244
        }
