source 'https://rubygems.org'

gem 'rails', '~> 4.2.1'
gem 'rails-api'
gem 'pg'

gem 'jbuilder', '~> 2.0'

gem 'settingslogic'
gem 'hashie'
gem 'groupdate'
gem 'kaminari'
gem 'activerecord-colored_log_subscriber'
gem 'aws-sdk', '~> 2'
gem 'mixpanel-ruby'
gem 'zazo-tools', github: 'noplanb/zazo-tools', tag: '1.0.0', require: 'zazo'


gem 'puma'
gem 'foreman'
gem 'figaro', github: 'asux/figaro', branch: 'feature/eb-set-command'
gem 'rollbar'
gem 'newrelic_rpm'

gem 'pry-rails'
gem 'awesome_print'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-pow', require: false
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rails_layout'
  gem 'rsense'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug', '= 1.3.3'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'vcr'
  gem 'timecop'
end
